<?php

return [
    'risk_schema_version' => 'trading_risk_v1_1',
    'action_risk_schema_version' => 'trading_action_risk_v1',
    'selected_parameters_schema_version' => 'trading_selected_parameters_v1',
    'trade_plan_schema_version' => 'trading_trade_plan_v1',
    'research_risk_required_artifacts' => ['sl_optimizer', 'tp_optimizer', 'reentry_research'],
    'decision_risk_required_artifacts' => ['tp_optimizer', 'sl_optimizer'],
    'allowed_artifact_types' => ['trade_episode_dataset','tp_optimizer','sl_optimizer','reentry_research','walk_forward_event_dataset','event_dataset_quality'],
    'statuses' => ['unavailable', 'partial', 'research_only', 'decision_ready', 'invalid'],
    'trade_plan_statuses' => ['unavailable', 'blocked', 'research_only', 'candidate_ready', 'available', 'invalid'],
    'action_specific_required' => true,
    'selected_parameter_required' => true,
    'dependency_blocker_statuses' => ['checksum_mismatch', 'schema_mismatch', 'ticker_mismatch', 'unresolved', 'missing_file'],
    'stale_blocks_decision_risk' => true,
    'quarantine_blocks_decision_risk' => true,
    'supported_risk_metric_keys' => ['expected_return_pct','expected_loss_pct','risk_reward_ratio','probability_tp_hit','probability_sl_hit','expected_drawdown_pct','cvar_pct','holding_days'],
    'position_sizing_capability_status' => 'not_implemented',
    'trade_plan_capability_status' => 'contract_only',
    'decision_risk_capability_status' => 'contract_only',
    'unavailable_reason_policy' => 'collect_all_blockers',
    'supported_action_risk_intents' => ['long_entry'],
    'supported_parameter_types' => ['percentage'],
    'supported_units' => ['percent'],
    'action_risk_gate_order' => ['candidate_available','candidate_schema_valid','candidate_status_ready','supported_intent','candidate_identity','parameter_evidence_available','parameter_schema_valid','ticker_identity_match','candidate_identity_match','tp_decision_usability','sl_decision_usability','selected_tp_available','selected_sl_available','source_checksum_available','dependency_resolved','source_not_stale','source_not_quarantined','supported_parameter_type','numeric_parameter_validity','geometry_calculation'],
    'action_risk_calculation_method' => 'action_risk_contract_v1',
    'rounding_precision' => 6,
    'net_metric_capability' => 'unavailable',
    'probabilistic_risk_capability' => 'unavailable',
    'capital_risk_capability' => 'not_implemented',
    'canonical_risk_source' => 'action_specific_risk',
];
