<?php

return [
    'allowed_roots' => [
        storage_path('app/trading_research'),
    ],
    'allowed_tickers' => ['BUMI', 'DEWA'],
    'checksum_algorithm' => 'sha256',
    'maximum_file_size' => 10 * 1024 * 1024,
    'maximum_json_depth' => 64,
    'path_traversal_protection' => true,
    'symlink_policy' => 'reject_escape',
    'quarantine_policy' => [
        'quarantine_invalid_when_requested' => true,
        'move_files' => false,
        'quarantine_conflicts' => true,
        'quarantine_modified_files' => true,
    ],
    'dependency_verification_policy' => [
        'required_checksum_mismatch_is_critical' => true,
        'optional_unresolved_is_warning' => true,
    ],
    'supported_artifact_types' => [
        'walk_forward_event_dataset' => ['walk_forward_event_dataset_v1'],
        'trade_episode_dataset' => ['trade_episode_dataset_v1'],
        'event_dataset_quality' => ['event_dataset_quality_v1'],
        'tp_optimizer' => ['tp_optimizer_v1'],
        'sl_optimizer' => ['sl_optimizer_v1_1'],
        'reentry_research' => ['reentry_research_v1_1'],
    ],
    'filename_patterns' => [
        'walk_forward_event_dataset' => '*event*dataset*.json',
        'trade_episode_dataset' => '*trade_episodes*.json',
        'event_dataset_quality' => '*quality*.json',
        'tp_optimizer' => '*tp_optimizer*.json',
        'sl_optimizer' => '*sl_optimizer*.json',
        'reentry_research' => '*reentry_research*.json',
    ],
    'staleness_days' => [
        'walk_forward_event_dataset' => 3650,
        'trade_episode_dataset' => 3650,
        'event_quality_report' => 3650,
        'tp_optimizer' => 3650,
        'sl_optimizer' => 3650,
        'reentry_research' => 3650,
    ],
    'warning_classification' => [
        'critical_keywords' => ['checksum_mismatch', 'logical_identity_conflict', 'invalid', 'critical'],
        'informational_keywords' => ['research-only', 'source SL/TP research-only input', 'selected null'],
    ],
    'quality_classification' => [
        'limited_warning_keywords' => ['high_unclassified_rate', 'ATR family unavailable', 'extreme_winner_dependency', 'CI lower bound'],
        'critical_warning_keywords' => ['checksum_mismatch', 'logical_identity_conflict', 'dependency checksum mismatch'],
    ],
    'usage_tiers' => ['none', 'research_only', 'decision_usable'],
    'unclassified_rate_thresholds' => [
        'reentry_research_v1_1' => 0.25,
    ],
    'selected_null_policy' => [
        'research_only_allowed' => true,
        'decision_requires_selected' => true,
    ],
    'stale_artifact_policy' => [
        'decision_excludes_stale' => true,
        'research_allows_stale_with_warning' => true,
    ],
    'decision' => [
        'schema_version' => 'trading_decision_v1_8',
        'service_contract_version' => 'basic_decision_v1_8',
        'supported_tickers' => ['BUMI', 'DEWA'],
        'required_research_artifacts' => ['trade_episode_dataset', 'tp_optimizer', 'sl_optimizer'],
        'required_decision_artifacts' => ['tp_optimizer', 'sl_optimizer'],
        'optional_artifacts' => ['walk_forward_event_dataset', 'event_dataset_quality', 'reentry_research'],
        'prediction_freshness_minutes' => 120,
        'allowed_actions' => ['WAIT', 'NO_TRADE'],
        'action_statuses' => ['normal', 'safe_downgrade', 'blocked', 'unsupported'],
        'recommendation_qualities' => ['unavailable', 'research_only', 'decision_ready'],
        'semantic_roles' => ['directional', 'regime', 'volatility', 'unknown'],
        'evidence_readiness' => ['unavailable', 'partial', 'research_ready', 'decision_ready', 'invalid'],
        'capability_readiness' => ['unavailable', 'partial', 'basic_only', 'action_selection_ready'],
        'action_eligibility' => ['ineligible', 'blocked', 'eligible_but_not_supported', 'eligible'],
        'decision_scopes' => ['entry_evaluation', 'position_management', 'observation_only', 'unsupported'],
        'position_contexts' => ['no_open_trade', 'open_trade', 'invalid_open_trade', 'unknown'],
        'position_management_statuses' => ['not_required', 'not_implemented', 'unavailable', 'blocked'],
        'prediction_requirements' => [
            'BUMI' => ['directional_required' => true, 'regime_optional' => true, 'regime_only_policy' => 'wait'],
            'DEWA' => ['directional_required' => true, 'regime_optional' => true, 'regime_only_policy' => 'wait'],
        ],
        'dependency_blocker_statuses' => ['checksum_mismatch', 'schema_mismatch', 'ticker_mismatch'],
        'unsupported_ticker_policy' => 'no_trade',
        'prediction_semantics' => [
            'up' => 'directional_up',
            'down' => 'directional_down',
            'neutral' => 'directional_neutral',
            'move' => 'regime_move',
            'no_move' => 'regime_no_move',
        ],
        'reason_codes' => [
            'PREDICTION_UNAVAILABLE','PREDICTION_INVALID','PREDICTION_STALE','RESEARCH_ARTIFACTS_AVAILABLE',
            'RESEARCH_ONLY_EVIDENCE','NO_DECISION_USABLE_TP','NO_DECISION_USABLE_SL','NO_DECISION_USABLE_REENTRY',
            'SELECTED_TP_UNAVAILABLE','SELECTED_SL_UNAVAILABLE','SELECTED_REENTRY_UNAVAILABLE','ARTIFACT_STALE',
            'ARTIFACT_QUARANTINED','DEPENDENCY_UNRESOLVED','DEPENDENCY_CHECKSUM_MISMATCH','HIGH_UNCLASSIFIED_RATE',
            'ATR_FAMILY_UNAVAILABLE','EXTREME_WINNER_DEPENDENCY','SAFE_DOWNGRADE_WAIT','SAFE_DOWNGRADE_NO_TRADE',
            'CONFIDENCE_ENGINE_NOT_IMPLEMENTED','RISK_ENGINE_NOT_IMPLEMENTED','TRADE_PLAN_NOT_IMPLEMENTED',
            'ACTION_CAPABILITY_NOT_IMPLEMENTED','UNSUPPORTED_TICKER','UNKNOWN_PREDICTION_SEMANTICS',
            'MULTIPLE_PREDICTIONS_AVAILABLE','DIRECTIONAL_PREDICTION_AVAILABLE','REGIME_PREDICTION_AVAILABLE',
            'DIRECTIONAL_PREDICTION_MISSING','REGIME_ONLY_NOT_DIRECTIONAL','PREDICTION_CONFLICT',
            'DUPLICATE_PREDICTION','OPEN_TRADE_PRESENT','OPEN_TRADE_INVALID','POSITION_MANAGEMENT_NOT_IMPLEMENTED',
            'EVIDENCE_RESEARCH_READY','EVIDENCE_DECISION_READY','ACTION_ELIGIBLE_BUT_NOT_SUPPORTED',
            'DECISION_FINGERPRINT_GENERATED','LEGACY_PREDICTION_INPUT_DEPRECATED','CONFLICTING_PREDICTION_INPUTS',
            'ACTION_SELECTION_NOT_IMPLEMENTED',
            'RESEARCH_RISK_EVIDENCE_AVAILABLE','RESEARCH_RISK_EVIDENCE_PARTIAL','DECISION_RISK_UNAVAILABLE',
            'ACTION_CANDIDATE_NOT_AVAILABLE','DECISION_USABLE_TP_UNAVAILABLE','DECISION_USABLE_SL_UNAVAILABLE',
            'SELECTED_TP_REQUIRED_FOR_RISK','SELECTED_SL_REQUIRED_FOR_RISK','RISK_METRICS_INCOMPLETE',
            'RISK_ARTIFACT_STALE','RISK_ARTIFACT_QUARANTINED','RISK_DEPENDENCY_UNRESOLVED',
            'POSITION_SIZING_NOT_IMPLEMENTED','DECISION_RISK_NOT_ACTION_SPECIFIC','TRADE_PLAN_UNAVAILABLE',
            'ACTION_CANDIDATE_REQUIRED_FOR_PLAN','DECISION_RISK_REQUIRED_FOR_PLAN','ENTRY_PARAMETER_UNAVAILABLE',
            'TAKE_PROFIT_PARAMETER_UNAVAILABLE','STOP_LOSS_PARAMETER_UNAVAILABLE','HOLDING_PARAMETER_UNAVAILABLE',
            'REENTRY_PARAMETER_UNAVAILABLE','TRADE_PLAN_CAPABILITY_NOT_IMPLEMENTED','RESEARCH_PARAMETER_NOT_PROMOTED',
            'ACTION_CANDIDATE_UNAVAILABLE','ACTION_CANDIDATE_BLOCKED','ACTION_CANDIDATE_OBSERVATION_ONLY',
            'ACTION_CANDIDATE_READY','ACTION_CANDIDATE_REJECTED','ACTION_CANDIDATE_INVALID',
            'LONG_ENTRY_CANDIDATE_REQUIRES_DIRECTIONAL_UP','DIRECTIONAL_SIGNAL_NOT_ELIGIBLE',
            'DECISION_READY_EVIDENCE_REQUIRED','DECISION_USABLE_TP_REQUIRED_FOR_CANDIDATE',
            'DECISION_USABLE_SL_REQUIRED_FOR_CANDIDATE','SELECTED_TP_REQUIRED_FOR_CANDIDATE',
            'SELECTED_SL_REQUIRED_FOR_CANDIDATE','CANDIDATE_ELIGIBLE_FOR_RISK_EVALUATION',
            'CANDIDATE_NOT_EXECUTABLE','ACTION_PROMOTION_NOT_IMPLEMENTED',
            'ACTION_CANDIDATE_AVAILABLE_NOT_PROMOTED','POSITION_MANAGEMENT_CANDIDATE_NOT_IMPLEMENTED',
            'ACTION_SELECTION_CANDIDATE_UNAVAILABLE','ACTION_SELECTION_CANDIDATE_BLOCKED','ACTION_SELECTION_CANDIDATE_INVALID','ACTION_SELECTION_CONFIDENCE_UNAVAILABLE','ACTION_SELECTION_CONFIDENCE_IDENTITY_MISMATCH','ACTION_SELECTION_RISK_UNAVAILABLE','ACTION_SELECTION_RISK_IDENTITY_MISMATCH','ACTION_SELECTION_TRADE_PLAN_UNAVAILABLE','ACTION_SELECTION_TRADE_PLAN_IDENTITY_MISMATCH','ACTION_SELECTION_CAPABILITY_DISABLED','ACTION_SELECTION_POLICY_NOT_IMPLEMENTED','CANDIDATE_ELIGIBLE_BUT_NOT_SELECTABLE','SELECTED_CANDIDATE_UNAVAILABLE','SAFETY_ACTION_WAIT_SELECTED','SAFETY_ACTION_NO_TRADE_SELECTED','ACTION_PROMOTION_NOT_APPLICABLE','ACTION_PROMOTION_SELECTED_CANDIDATE_REQUIRED','ACTION_PROMOTION_CAPABILITY_DISABLED','ACTION_PROMOTION_POLICY_NOT_IMPLEMENTED','ACTION_PROMOTION_BLOCKED','ACTION_PROMOTION_ELIGIBLE_BUT_DISABLED','PROMOTED_ACTION_UNAVAILABLE','EXECUTABLE_ACTION_UNAVAILABLE','EXECUTION_CAPABILITY_NOT_IMPLEMENTED',
            'ACTION_RISK_UNAVAILABLE','ACTION_RISK_CANDIDATE_REQUIRED','ACTION_RISK_CANDIDATE_NOT_READY','ACTION_RISK_UNSUPPORTED_INTENT','ACTION_RISK_PARAMETER_EVIDENCE_REQUIRED','ACTION_RISK_PARAMETER_EVIDENCE_RESEARCH_ONLY','ACTION_RISK_TP_DECISION_USABLE_REQUIRED','ACTION_RISK_SL_DECISION_USABLE_REQUIRED','ACTION_RISK_SELECTED_TP_REQUIRED','ACTION_RISK_SELECTED_SL_REQUIRED','ACTION_RISK_IDENTITY_MISMATCH','ACTION_RISK_DEPENDENCY_UNRESOLVED','ACTION_RISK_SOURCE_STALE','ACTION_RISK_SOURCE_QUARANTINED','ACTION_RISK_PARAMETER_TYPE_UNSUPPORTED','ACTION_RISK_PARAMETER_INVALID','ACTION_RISK_GROSS_GEOMETRY_AVAILABLE','ACTION_RISK_NET_METRICS_UNAVAILABLE','ACTION_RISK_PROBABILITY_METRICS_UNAVAILABLE','ACTION_RISK_CAPITAL_METRICS_UNAVAILABLE','ACTION_RISK_NON_EXECUTABLE_REFERENCE','TRADE_PLAN_MATERIALIZATION_NOT_IMPLEMENTED',
            'TRADE_PLAN_REFERENCE_UNAVAILABLE','TRADE_PLAN_CANDIDATE_REQUIRED','TRADE_PLAN_CANDIDATE_NOT_READY','TRADE_PLAN_SELECTED_PARAMETERS_REQUIRED','TRADE_PLAN_ACTION_RISK_REQUIRED','TRADE_PLAN_ACTION_RISK_NOT_EVALUATED','TRADE_PLAN_ENTRY_REFERENCE_REQUIRED','TRADE_PLAN_ENTRY_REFERENCE_STALE','TRADE_PLAN_IDENTITY_MISMATCH','TRADE_PLAN_RISK_GEOMETRY_MISMATCH','TRADE_PLAN_PARAMETER_READY','TRADE_PLAN_REFERENCE_MATERIALIZED','TRADE_PLAN_REFERENCE_ONLY','TRADE_PLAN_NON_EXECUTABLE','TRADE_PLAN_EXECUTION_NOT_IMPLEMENTED','TRADE_PLAN_HOLDING_NOT_IMPLEMENTED','TRADE_PLAN_REENTRY_NOT_IMPLEMENTED','TRADE_PLAN_POSITION_SIZING_NOT_IMPLEMENTED','TRADE_PLAN_POSITION_MANAGEMENT_NOT_IMPLEMENTED','TRADE_PLAN_RESEARCH_PARAMETER_REJECTED',
        ],
    ],
];
