<?php
namespace App\Services\Trading;
class EntryReferenceSelectionPolicyService
{public function __construct(protected ?array $config=null){$this->config??=config('trading_reference_selection');}
 public function evaluate(array $ctx):array{$p=$ctx['entry_reference_selection_policy']??null;$candidate=$ctx['action_candidate']??null;$approval=$ctx['portfolio_approval']??null;$codes=[];$warnings=[];$blockers=[];$checks=[];$status='unavailable';$elig='policy_unavailable';
  if(!is_array($p))$this->add($codes,'ENTRY_REFERENCE_SELECTION_POLICY_UNAVAILABLE',$blockers);elseif(($p['schema_version']??null)!==$this->config['entry_policy_schema_version']||$this->invalid($p,'entry',$codes,$blockers)){$status='invalid';$elig='invalid';}else{if(($p['candidate_id']??null)!==($candidate['candidate_id']??null)||($p['portfolio_id']??null)!==($approval['portfolio_id']??null)){$status='blocked';$elig='identity_mismatch';$this->add($codes,'ENTRY_REFERENCE_SELECTION_POLICY_IDENTITY_MISMATCH',$blockers);}else{$checks=$this->checks($p,$ctx);$failed=false;$unavail=false;foreach($checks as $c){if($c['passed']===false)$failed=true;if($c['passed']===null)$unavail=true;}if(!($p['approved_for_reference_selection']??false)){$status='denied_reference_selection';$elig='denied_reference_selection';$this->add($codes,'ENTRY_REFERENCE_SELECTION_DENIED',$blockers);}elseif($failed){$status='blocked';$elig='requirement_failed';$this->add($codes,'ENTRY_REFERENCE_SELECTION_REQUIREMENT_FAILED',$blockers);}elseif($unavail){$status='incomplete';$elig='requirement_unavailable';$this->add($codes,'ENTRY_REFERENCE_SELECTION_REQUIREMENT_UNAVAILABLE',$blockers);}else{$status='eligible_for_reference_selection';$elig='eligible_for_reference_selection';$this->add($codes,'ENTRY_REFERENCE_SELECTION_ELIGIBLE');}$this->add($codes,'ENTRY_REFERENCE_SELECTION_REFERENCE_ONLY');}}
  return ['schema_version'=>$this->config['entry_policy_evaluation_schema_version'],'status'=>$status,'selection_scope'=>'entry_candidate_reference','policy_id'=>$p['policy_id']??null,'policy_version'=>$p['policy_version']??null,'candidate_id'=>$p['candidate_id']??($candidate['candidate_id']??null),'portfolio_id'=>$p['portfolio_id']??($approval['portfolio_id']??null),'requirement_checks'=>$checks,'all_required_checks_passed'=>$status==='eligible_for_reference_selection','reference_selection_allowed'=>$status==='eligible_for_reference_selection','production_selection_allowed'=>false,'execution_allowed'=>false,'eligibility'=>$elig,'reason_codes'=>$this->ordered($codes),'warnings'=>$this->ordered($warnings),'blockers'=>$this->ordered($blockers),'metadata'=>[]];}
 protected function checks($p,$ctx){$candidate=$ctx['action_candidate']??[];$risk=$ctx['risk']??[];$plan=$ctx['trade_plan']??[];$approval=$ctx['portfolio_approval']??[];$map=['candidate_ready'=>[$candidate,'candidate_ready'],'candidate_confidence_available'=>[$ctx['confidence']['trade_action_confidence']??['status'=>'unavailable'],['available','candidate_specific_available']],'action_risk_evaluated'=>[$risk['action_specific_risk']??[],'evaluated_reference'],'reference_plan_materialized'=>[$plan['reference_plan']??$plan,'materialized_reference'],'capital_risk_evaluated'=>[$risk['capital_risk']??[],'evaluated_reference'],'position_sizing_reference_available'=>[$risk['position_sizing']??[],'reference_sized'],'execution_readiness_reference_available'=>[$plan['execution_readiness']??[],'reference_ready'],'portfolio_risk_evaluated'=>[$risk['portfolio_risk']??[],'evaluated_reference'],'portfolio_reference_approved'=>[$approval['approval_result']??[],'approved']];$out=[];foreach($p['requirements']??[] as $k=>$req){$src=$map[$k][0]??null;$expect=$map[$k][1]??null;$evaluated=is_array($src);$st=$src['status']??(($src['reference_approved']??false)?'approved':null);$passed=null;if($evaluated)$passed=is_array($expect)?in_array($st,$expect,true):$st===$expect;$out[]=['key'=>$k,'required'=>(bool)$req,'evaluated'=>$evaluated,'passed'=>$req?$passed:true,'source_status'=>$st,'reason_code'=>'ENTRY_REFERENCE_SELECTION_'.$k];}return $out;}
 protected function invalid($p,$scope,&$codes,&$blockers){$bad=false;foreach(['policy_id','policy_version','selection_scope','selection_mode','candidate_id','portfolio_id','portfolio_approval_id','requirements','source'] as $k)if(empty($p[$k]))$bad=true;if(($p['selection_scope']??null)!=='entry_candidate_reference'||($p['selection_mode']??null)!=='single_candidate_reference')$bad=true;foreach(array_keys($p['requirements']??[]) as $k)if(!in_array($k,$this->config['entry_requirement_keys'],true))$bad=true;if(($p['approved_for_production_selection']??false)||($p['approved_for_execution']??false))$bad=true;if($bad)$this->add($codes,'ENTRY_REFERENCE_SELECTION_POLICY_INVALID',$blockers);return $bad;}
 protected function add(&$c,$code,&$target=null){if(!in_array($code,$c,true))$c[]=$code;if(is_array($target)&&!in_array($code,$target,true))$target[]=$code;}protected function ordered($c){sort($c);return array_values(array_unique($c));}}
