<?php
namespace App\Services\Trading;
use Carbon\Carbon;
class ExposureAggregationService
{
 public function __construct(protected ?array $config=null){$this->config??=config('trading_portfolio_risk');}
 public function aggregate(array $context): array
 {
  $portfolio=$context['portfolio_context']??null; $positions=$context['position_snapshots']??null; $decisionAt=$context['decision_at']??null; $codes=[];$warnings=[];$gates=[];
  $pvalid=$this->validPortfolio($portfolio,$decisionAt); $positionsAvailable=is_array($positions); $seen=[];$gross=0.0;$risk=0.0;$ticker=[];$sector=[];$riskComplete=true;$sectorComplete=true;$currencyComplete=true;$validPositions=true;
  if($positionsAvailable){foreach($positions as $pos){$id=$pos['position_id']??null; if(!$this->validPosition($pos,$portfolio,$decisionAt)||isset($seen[$id])){$validPositions=false;} $seen[$id]=true; if(($pos['currency']??null)!==($portfolio['base_currency']??null))$currencyComplete=false; $notional=(float)($pos['reference_notional']??0); $car=$pos['capital_at_risk']??null; if($car===null||!is_numeric($car)){$riskComplete=false;$car=0;} $gross+=$notional; $risk+=(float)$car; $t=$pos['ticker']??'UNKNOWN'; $ticker[$t]['notional']=($ticker[$t]['notional']??0)+$notional; $ticker[$t]['capital_at_risk']=($ticker[$t]['capital_at_risk']??0)+(float)$car; if(empty($pos['sector'])){$sectorComplete=false;} else {$s=$pos['sector']; $sector[$s]['notional']=($sector[$s]['notional']??0)+$notional; $sector[$s]['capital_at_risk']=($sector[$s]['capital_at_risk']??0)+(float)$car;}}}
  foreach([['portfolio_context_available',true,is_array($portfolio),'PORTFOLIO_CONTEXT_UNAVAILABLE'],['portfolio_context_valid',is_array($portfolio),$pvalid,'PORTFOLIO_CONTEXT_INVALID'],['portfolio_context_fresh',is_array($portfolio),is_array($portfolio)?$this->fresh($portfolio['as_of']??null,$decisionAt):null,'PORTFOLIO_CONTEXT_STALE'],['position_snapshots_available',true,$positionsAvailable,'PORTFOLIO_POSITION_SNAPSHOT_UNAVAILABLE'],['position_schemas_valid',$positionsAvailable,$positionsAvailable?$validPositions:null,'PORTFOLIO_POSITION_SNAPSHOT_INVALID'],['portfolio_identity_consistency',$positionsAvailable,$positionsAvailable?$validPositions:null,'PORTFOLIO_IDENTITY_MISMATCH'],['currency_consistency',$positionsAvailable,$positionsAvailable?$currencyComplete:null,'PORTFOLIO_CURRENCY_MISMATCH'],['supported_position_type',$positionsAvailable,$positionsAvailable?$validPositions:null,'PORTFOLIO_POSITION_SNAPSHOT_INVALID'],['quantity_price_validity',$positionsAvailable,$positionsAvailable?$validPositions:null,'PORTFOLIO_POSITION_SNAPSHOT_INVALID'],['notional_reconciliation',$positionsAvailable,$positionsAvailable?$validPositions:null,'PORTFOLIO_POSITION_SNAPSHOT_INVALID'],['capital_risk_completeness',$positionsAvailable,$positionsAvailable?$riskComplete:null,'PORTFOLIO_EXPOSURE_PARTIAL'],['ticker_aggregation',$positionsAvailable,$positionsAvailable&&$validPositions,'PORTFOLIO_EXPOSURE_AGGREGATED_REFERENCE'],['optional_sector_aggregation',$positionsAvailable,$positionsAvailable?$sectorComplete:null,'PORTFOLIO_SECTOR_DATA_INCOMPLETE'],['final_data_quality_classification',true,$pvalid&&$positionsAvailable&&$validPositions&&$currencyComplete,'PORTFOLIO_EXPOSURE_AGGREGATED_REFERENCE']] as [$n,$e,$pass,$code]){$gates[]=$this->gate($n,$e,$pass,$pass===true?'passed':'blocking',$code); if($pass===false)$this->add($codes,$code);}
  $status=($pvalid&&$positionsAvailable&&$validPositions&&$currencyComplete)?($riskComplete?'aggregated_reference':'partial'):'unavailable'; if($status==='aggregated_reference')$this->add($codes,'PORTFOLIO_EXPOSURE_AGGREGATED_REFERENCE'); if($status==='partial')$this->add($codes,'PORTFOLIO_EXPOSURE_PARTIAL'); if(!$positionsAvailable)$this->add($codes,'PORTFOLIO_NO_EMPTY_PORTFOLIO_ASSUMPTION'); $this->add($codes,'PORTFOLIO_CORRELATION_RISK_NOT_IMPLEMENTED');
  $r=['schema_version'=>$this->config['exposure_aggregation_schema_version'],'status'=>$status,'portfolio_id'=>$portfolio['portfolio_id']??null,'base_currency'=>$portfolio['base_currency']??null,'position_count'=>$positionsAvailable?count($positions):0,'metrics'=>['gross_notional'=>$status==='unavailable'?null:$gross,'gross_capital_at_risk'=>$status==='unavailable'?null:$risk,'net_notional'=>$status==='unavailable'?null:$gross,'ticker_exposure'=>$ticker,'sector_exposure'=>$sector,'cash_exposure'=>$portfolio['available_cash']??null],'data_quality'=>['positions_complete'=>$positionsAvailable&&$validPositions,'risk_values_complete'=>$riskComplete,'sector_values_complete'=>$sectorComplete,'currency_values_complete'=>$currencyComplete],'reason_codes'=>$this->ordered($codes),'warnings'=>$this->ordered($warnings),'metadata'=>['correlation_risk'=>'not_implemented'],'aggregation_gates'=>$this->sortGates($gates)]; $this->validateExposureAggregation($r); return $r;
 }
 public function validateExposureAggregation(array $r):void{if(($r['schema_version']??null)!==$this->config['exposure_aggregation_schema_version'])throw new \InvalidArgumentException('invalid exposure schema'); if(!in_array($r['status']??null,['unavailable','partial','aggregated_reference','invalid'],true))throw new \InvalidArgumentException('invalid exposure status'); if(count($r['reason_codes'])!==count(array_unique($r['reason_codes'])))throw new \InvalidArgumentException('duplicate exposure reason');}
 protected function validPortfolio($p,$d):bool{return is_array($p)&&($p['schema_version']??null)===$this->config['portfolio_context_schema_version']&&($p['status']??null)==='reference_only'&&!empty($p['portfolio_id'])&&!empty($p['base_currency'])&&is_numeric($p['capital_base']??null)&&$p['capital_base']>0&&!empty($p['source'])&&($p['approved_for_execution']??null)===false&&$this->fresh($p['as_of']??null,$d);} protected function validPosition($pos,$p,$d):bool{if(!is_array($pos)||($pos['schema_version']??null)!==$this->config['position_snapshot_schema_version']||($pos['status']??null)!=='reference_only')return false; if(($pos['portfolio_id']??null)!==($p['portfolio_id']??null)||!in_array($pos['side']??null,$this->config['supported_position_sides'],true))return false; if(!is_numeric($pos['quantity']??null)||$pos['quantity']<=0||!is_numeric($pos['reference_price']??null)||$pos['reference_price']<=0)return false; if(abs(($pos['reference_notional']??0)-$pos['quantity']*$pos['reference_price'])>$this->config['reconciliation_tolerance'])return false; return !empty($pos['position_id'])&&!empty($pos['ticker'])&&!empty($pos['currency'])&&!empty($pos['source'])&&($pos['approved_for_execution']??null)===false&&$this->fresh($pos['as_of']??null,$d);} protected function fresh($a,$d):bool{if(!$a||!$d)return false;try{$x=Carbon::parse($a);$y=Carbon::parse($d);}catch(\Throwable){return false;}return $x->lessThanOrEqualTo($y);} protected function gate($gate,$evaluated,$passed,$severity,$code,$details=[]):array{return compact('gate','evaluated','passed','severity','code','details');} protected function add(&$c,$v):void{if(!in_array($v,$c,true))$c[]=$v;} protected function ordered($c):array{sort($c);return array_values(array_unique($c));} protected function sortGates($g):array{$o=array_flip($this->config['aggregation_gate_order']);usort($g,fn($a,$b)=>($o[$a['gate']]??999)<=>($o[$b['gate']]??999));return $g;}
}
