<?php
namespace App\Services\Trading;
use Carbon\Carbon;
class PositionManagementAuthorizationService
{public function __construct(protected ?array $config=null){$this->config??=config('trading_position_management_approval');}
 public function validate(array $ctx):array{$auth=$ctx['management_authorization']??null;$policy=$ctx['management_approval_policy_evaluation']??null;$plan=$ctx['action_plan']??null;$impact=$ctx['impact_simulation']??null;$decisionAt=$ctx['decision_at']??null;$codes=[];$warnings=[];$blockers=[];$status='unavailable';$elig='authorization_unavailable';$identity=false;$planOk=false;$impactOk=false;$policyOk=false;$fpOk=false;$timeOk=false;$refOk=false;
  if(!is_array($auth)){$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_UNAVAILABLE',$blockers);} elseif(($auth['schema_version']??null)!==$this->config['authorization_schema_version']){$status='invalid';$elig='authorization_invalid';$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_INVALID',$blockers);} else {
   $invalid=false;if(!in_array($auth['authorization_type']??null,$this->config['supported_authorization_types'],true)||!in_array($auth['authorization_decision']??null,$this->config['supported_authorization_decisions'],true)||($auth['approval_scope']??null)!=='management_action_reference'||empty($auth['authorization_id']))$invalid=true;if(empty($auth['issued_by']))$invalid=true;if(($auth['production_authority']??false)||($auth['execution_authority']??false))$invalid=true;
   $identity=($auth['portfolio_id']??null)===($policy['portfolio_id']??null)&&($auth['position_id']??null)===($policy['position_id']??null)&&($auth['management_candidate_id']??null)===($policy['management_candidate_id']??null);
   $planOk=($auth['action_plan_id']??null)===($plan['action_plan_id']??null)&&($auth['proposed_management_action']??null)===($plan['proposed_management_action']??null)&&((float)($auth['proposed_quantity_reference']??-1)===(float)($plan['quantity_plan']['proposed_quantity_reference']??-2));
   $impactOk=($impact['action_plan_id']??($plan['action_plan_id']??null))===($plan['action_plan_id']??null)&&($impact['position_id']??null)===($plan['position_id']??null);
   $policyOk=($auth['policy_id']??null)===($policy['policy_id']??null)&&($auth['policy_version']??null)===($policy['policy_version']??null);
   $fpOk=($auth['approval_context_fingerprint']??null)===($policy['metadata']['management_approval_context_fingerprint']??null);
   $time=$this->timeValid($auth,$decisionAt);$timeOk=$time==='valid';
   foreach([[$identity,'POSITION_MANAGEMENT_AUTHORIZATION_IDENTITY_MISMATCH'],[$planOk,'POSITION_MANAGEMENT_AUTHORIZATION_ACTION_PLAN_MISMATCH'],[$policyOk,'POSITION_MANAGEMENT_AUTHORIZATION_POLICY_MISMATCH'],[$fpOk,'POSITION_MANAGEMENT_AUTHORIZATION_CONTEXT_FINGERPRINT_MISMATCH']] as [$ok,$code])if(!$ok){$invalid=true;$this->add($codes,$code,$blockers);} if(!$planOk)$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_QUANTITY_MISMATCH',$blockers);
   if($time==='future'||$time==='invalid'){$invalid=true;$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_INVALID',$blockers);} if($time==='expired'){$status='expired';$elig='authorization_expired';$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_EXPIRED',$blockers);} elseif($invalid){$status='invalid';$elig='authorization_invalid';$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_INVALID',$blockers);} else {if($auth['authorization_decision']==='approve_reference'){$status='valid_reference_authorization';$elig='valid_reference_authorization';$refOk=true;$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_REFERENCE_APPROVE');}elseif($auth['authorization_decision']==='deny_reference'){$status='denied_reference';$elig='authorization_denied';$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_REFERENCE_DENIED',$blockers);}else{$status='review_only';$elig='authorization_review_only';$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_REVIEW_ONLY',$blockers);}}
  }
  foreach(['POSITION_MANAGEMENT_AUTHORIZATION_PRODUCTION_AUTHORITY_UNAVAILABLE','POSITION_MANAGEMENT_AUTHORIZATION_EXECUTION_AUTHORITY_UNAVAILABLE'] as $c)$this->add($codes,$c,$blockers);$this->add($codes,'POSITION_MANAGEMENT_AUTHORIZATION_NOT_CRYPTOGRAPHICALLY_VERIFIED',$warnings);
  $r=['schema_version'=>$this->config['authorization_validation_schema_version'],'status'=>$status,'authorization_id'=>$auth['authorization_id']??null,'authorization_decision'=>$auth['authorization_decision']??null,'approval_scope'=>$auth['approval_scope']??null,'identity_valid'=>$identity,'action_plan_binding_valid'=>$planOk,'impact_binding_valid'=>$impactOk,'policy_binding_valid'=>$policyOk,'context_fingerprint_valid'=>$fpOk,'time_valid'=>$timeOk,'reference_authority_valid'=>$refOk,'production_authority_valid'=>false,'execution_authority_valid'=>false,'eligibility'=>$elig,'reason_codes'=>$this->ordered($codes),'warnings'=>$this->ordered($warnings),'blockers'=>$this->ordered($blockers),'metadata'=>['not_cryptographically_verified'=>true]];return $r;}
 protected function timeValid($a,$decisionAt):string{try{$issued=Carbon::parse($a['issued_at']??'');$expires=Carbon::parse($a['expires_at']??'');$decision=Carbon::parse($decisionAt??'');}catch(\Throwable){return 'invalid';}if($issued->greaterThan($decision))return 'future';if($expires->lessThanOrEqualTo($issued))return 'invalid';if($expires->lessThanOrEqualTo($decision))return 'expired';return 'valid';}
 protected function add(&$c,$code,&$target=null):void{if(!in_array($code,$c,true))$c[]=$code;if(is_array($target)&&!in_array($code,$target,true))$target[]=$code;} protected function ordered($c):array{sort($c);return array_values(array_unique($c));}}
