<?php
namespace App\Services\Trading;
class PositionManagementApprovalPolicyService
{
 public function __construct(protected ?array $config=null){$this->config??=config('trading_position_management_approval');}
 public function evaluate(array $ctx):array{$candidate=$ctx['management_candidate']??null;$risk=$ctx['management_risk']??null;$review=$ctx['review_plan']??null;$actionPolicy=$ctx['action_policy_evaluation']??null;$plan=$ctx['action_plan']??null;$impact=$ctx['impact_simulation']??null;$policy=$ctx['management_approval_policy']??null;$codes=[];$warnings=[];$blockers=[];$checks=[];$status='unavailable';$elig='policy_unavailable';$portfolioId=$policy['portfolio_id']??($ctx['portfolio_context']['portfolio_id']??null);
  if(!is_array($policy)){$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_UNAVAILABLE',$blockers);} elseif(($policy['schema_version']??null)!==$this->config['approval_policy_schema_version']||$this->policyInvalid($policy,$codes,$blockers)){$status='invalid';$elig='invalid';}
  if(is_array($policy)&&$status!=='invalid'){
   if(($policy['approval_scope']??null)!=='management_action_reference'){$status='invalid';$elig='invalid';$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_INVALID',$blockers);} else {
    $identityOk=is_array($candidate)&&is_array($plan)&&($policy['position_id']??null)===($candidate['position_id']??null)&&($policy['management_candidate_id']??null)===($candidate['candidate_id']??null)&&($policy['action_plan_id']??null)===($plan['action_plan_id']??null)&&($policy['proposed_management_action']??null)===($plan['proposed_management_action']??null);
    if(!$identityOk){$status='blocked';$elig='identity_mismatch';$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_IDENTITY_MISMATCH',$blockers);} else {
     $checks=$this->buildChecks($policy,$candidate,$risk,$review,$actionPolicy,$plan,$impact,$portfolioId);$failed=false;$unavailable=false;foreach($checks as $c){if($c['passed']===false)$failed=true;if($c['passed']===null)$unavailable=true;}
     if($failed){$status='blocked';$elig='approval_policy_incomplete';$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_REQUIREMENT_FAILED',$blockers);} elseif($unavailable){$status='incomplete';$elig='approval_policy_incomplete';$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_REQUIREMENT_UNAVAILABLE',$blockers);} else {$status='eligible_for_authorization';$elig='eligible_for_reference_authorization';$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_ELIGIBLE_FOR_AUTHORIZATION');}
     $this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_REFERENCE_ONLY');
    }
   }
  }
  $fingerprint=$this->approvalContextFingerprint($ctx+['management_approval_policy'=>$policy]);
  $r=['schema_version'=>$this->config['approval_policy_evaluation_schema_version'],'status'=>$status,'policy_id'=>$policy['policy_id']??null,'policy_version'=>$policy['policy_version']??null,'approval_scope'=>$policy['approval_scope']??'management_action_reference','portfolio_id'=>$portfolioId,'position_id'=>$policy['position_id']??($candidate['position_id']??null),'management_candidate_id'=>$policy['management_candidate_id']??($candidate['candidate_id']??null),'action_plan_id'=>$policy['action_plan_id']??($plan['action_plan_id']??null),'proposed_management_action'=>$policy['proposed_management_action']??($plan['proposed_management_action']??null),'requirement_checks'=>$checks,'all_required_checks_passed'=>$status==='eligible_for_authorization','authorization_required'=>true,'eligibility'=>$elig,'reason_codes'=>$this->ordered($codes),'warnings'=>$this->ordered($warnings),'blockers'=>$this->ordered($blockers),'metadata'=>['management_approval_context_fingerprint'=>$fingerprint,'not_approval'=>true]]; $this->validateEvaluation($r);return $r;}
 protected function buildChecks($policy,$candidate,$risk,$review,$actionPolicy,$plan,$impact,$portfolioId):array{$map=['management_candidate_valid'=>[$candidate,'policy_hypothesis','trading_position_management_candidate_v1','POSITION_MANAGEMENT_APPROVAL_CANDIDATE_VALID'],'management_risk_evaluated'=>[$risk,['condition_risk_observed','evaluated_reference'],'trading_position_management_risk_v1','POSITION_MANAGEMENT_APPROVAL_RISK_EVALUATED'],'review_context_ready'=>[$review,'review_context_ready','trading_position_management_review_plan_v1','POSITION_MANAGEMENT_APPROVAL_REVIEW_READY'],'action_policy_matched'=>[$actionPolicy,'matched_reference_rule','trading_position_management_action_policy_evaluation_v1','POSITION_MANAGEMENT_APPROVAL_ACTION_POLICY_MATCHED'],'action_plan_materialized'=>[$plan,'materialized_reference','trading_position_management_action_plan_v1','POSITION_MANAGEMENT_APPROVAL_ACTION_PLAN_MATERIALIZED'],'impact_simulated'=>[$impact,'simulated_reference','trading_position_management_impact_v1','POSITION_MANAGEMENT_APPROVAL_IMPACT_SIMULATED'],'position_impact_reconciled'=>[$impact,'simulated_reference','trading_position_management_impact_v1','POSITION_MANAGEMENT_APPROVAL_POSITION_IMPACT_RECONCILED'],'portfolio_impact_available'=>[$impact['portfolio_impact']??null,'simulated_reference','trading_position_management_impact_v1','POSITION_MANAGEMENT_APPROVAL_PORTFOLIO_IMPACT_AVAILABLE'],'portfolio_identity_reconciled'=>[$impact['portfolio_impact']??null,'simulated_reference','trading_position_management_impact_v1','POSITION_MANAGEMENT_APPROVAL_PORTFOLIO_IDENTITY_RECONCILED'],'authorization_required'=>[['status'=>'required'],'required','trading_position_management_approval_policy_v1','POSITION_MANAGEMENT_PORTFOLIO_APPROVAL_AUTHORIZATION_REQUIRED']];$out=[];foreach($policy['requirements']??[] as $key=>$required){$src=$map[$key][0]??null;$expect=$map[$key][1]??null;$schema=$map[$key][2]??null;$code=$map[$key][3]??'POSITION_MANAGEMENT_APPROVAL_POLICY_REQUIREMENT_UNAVAILABLE';$evaluated=is_array($src);$status=$src['status']??null;$passed=null;if($evaluated){$passed=is_array($expect)?in_array($status,$expect,true):$status===$expect;if($key==='portfolio_identity_reconciled')$passed=$passed&&($policy['portfolio_id']??null)===$portfolioId;} $out[]=['key'=>$key,'required'=>(bool)$required,'evaluated'=>$evaluated,'passed'=>$required?$passed:true,'source_schema'=>$schema,'source_status'=>$status,'reason_code'=>$code];}return $out;}
 public function approvalContextFingerprint(array $ctx):string{$candidate=$ctx['management_candidate']??[];$risk=$ctx['management_risk']??[];$review=$ctx['review_plan']??[];$actionPolicy=$ctx['action_policy_evaluation']??[];$plan=$ctx['action_plan']??[];$impact=$ctx['impact_simulation']??[];$policy=$ctx['management_approval_policy']??[];$payload=['context_schema_version'=>'trading_position_management_approval_context_v1','decision_at'=>$ctx['decision_at']??null,'portfolio_id'=>$policy['portfolio_id']??($ctx['portfolio_context']['portfolio_id']??null),'position_id'=>$plan['position_id']??null,'management_candidate_id'=>$candidate['candidate_id']??null,'candidate_type'=>$candidate['candidate_type']??null,'management_risk_schema'=>$risk['schema_version']??null,'management_risk_status'=>$risk['status']??null,'review_plan_schema'=>$review['schema_version']??null,'review_plan_status'=>$review['status']??null,'action_policy_id'=>$actionPolicy['policy_id']??null,'action_policy_version'=>$actionPolicy['policy_version']??null,'action_policy_rule'=>$actionPolicy['matched_rule']['rule_id']??null,'action_plan_id'=>$plan['action_plan_id']??null,'proposed_action'=>$plan['proposed_management_action']??null,'quantity_mode'=>$plan['quantity_plan']['mode']??null,'proposed_quantity'=>$plan['quantity_plan']['proposed_quantity_reference']??null,'remaining_quantity'=>$plan['quantity_plan']['remaining_quantity_reference']??null,'reference_price_identity'=>$plan['price_basis']??null,'impact_schema'=>$impact['schema_version']??null,'impact_status'=>$impact['status']??null,'local_impact'=>$impact['position_impact']??null,'portfolio_impact'=>$impact['portfolio_impact']??null,'approval_policy_id'=>$policy['policy_id']??null,'approval_policy_version'=>$policy['policy_version']??null];return hash('sha256',json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION));}
 protected function policyInvalid($p,&$codes,&$blockers):bool{$bad=false;foreach(['policy_id','policy_version','approval_scope','portfolio_id','position_id','management_candidate_id','action_plan_id','proposed_management_action','requirements','source'] as $k)if(empty($p[$k]))$bad=true;if(!in_array($p['proposed_management_action']??null,$this->config['supported_proposed_actions'],true))$bad=true;foreach(array_keys($p['requirements']??[]) as $k)if(!in_array($k,$this->config['supported_requirement_keys'],true))$bad=true;if(($p['approved_for_production']??false)||($p['approved_for_execution']??false))$bad=true;if($bad)$this->add($codes,'POSITION_MANAGEMENT_APPROVAL_POLICY_INVALID',$blockers);return $bad;}
 public function validateEvaluation($r):void{if(($r['schema_version']??null)!==$this->config['approval_policy_evaluation_schema_version'])throw new \InvalidArgumentException('bad approval policy eval schema');if(($r['status']??null)==='eligible_for_authorization'&&!$r['all_required_checks_passed'])throw new \InvalidArgumentException('eligible with failed requirements');}
 protected function add(&$c,$code,&$target=null):void{if(!in_array($code,$c,true))$c[]=$code;if(is_array($target)&&!in_array($code,$target,true))$target[]=$code;} protected function ordered($c):array{sort($c);return array_values(array_unique($c));}
}
