<?php
namespace App\Services\Trading;
class PositionManagementActionPlanService
{
 public function __construct(protected ?array $config=null){$this->config??=config('trading_position_management_plan');}
 public function build(array $ctx):array{$eval=$ctx['action_policy_evaluation']??null;$pos=$ctx['managed_position']??($ctx['position']??null);$state=$ctx['position_state']??null;$risk=$ctx['management_risk']??null;$codes=[];$warnings=[];$blockers=[];$status='unavailable';$elig='action_policy_evaluation_unavailable';$action=null;$mode=null;$cur=null;$prop=null;$rem=null;$price=null;$priceStatus='unavailable';
  if(!is_array($eval)||($eval['status']??null)!=='matched_reference_rule'){$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_UNAVAILABLE',$blockers);$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_POLICY_REQUIRED',$blockers);} else {$action=$eval['proposed_action'];$mode=$eval['quantity_mode'];}
  if(!is_array($pos)){$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_UNAVAILABLE',$blockers);} else {$cur=$pos['quantity']??null;}
  if(!is_array($risk))$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_RISK_REQUIRED',$blockers);
  if(is_array($eval)&&is_array($pos)&&(($eval['position_id']??null)!==($pos['position_id']??null))){$elig='identity_mismatch';$status='blocked';$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_IDENTITY_MISMATCH',$blockers);} 
  $snap=$state['price_snapshot']??[]; $price=$snap['current_reference_price']??($state['current_reference_price']??null); if(is_numeric($price))$priceStatus='reference_ready'; else $this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_UNAVAILABLE',$blockers);
  if($action&&is_numeric($cur)&&$cur>0&&is_numeric($price)){ $rule=$eval['matched_rule']??[]; if($action==='exit_position'&&$mode==='full_position'){$prop=(float)$cur;$rem=0.0;$this->add($codes,'POSITION_MANAGEMENT_IMPACT_FULL_EXIT_REFERENCE');}
   elseif($action==='reduce_position'&&$mode==='explicit_units'&&is_numeric($rule['explicit_units']??null)){$prop=(float)$rule['explicit_units'];$rem=(float)$cur-$prop;}
   elseif($action==='reduce_position'&&$mode==='explicit_fraction'&&is_numeric($rule['explicit_fraction']??null)){$prop=round((float)$cur*(float)$rule['explicit_fraction'],$this->config['quantity_precision']);$rem=round((float)$cur-$prop,$this->config['quantity_precision']);}
   if($prop!==null&&($prop<=0||$prop>$cur||$rem<0||($action==='reduce_position'&&$rem<=0)||($action==='exit_position'&&abs($rem)>$this->config['reconciliation_tolerance']))){$prop=null;$rem=null;$status='invalid';$elig='quantity_invalid';$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_QUANTITY_INVALID',$blockers);} }
  if($prop!==null){$status='materialized_reference';$elig='materialized_reference';$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_MATERIALIZED_REFERENCE');$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_NON_EXECUTABLE',$blockers);$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_ORDER_NOT_IMPLEMENTED',$blockers);$this->add($codes,'POSITION_MANAGEMENT_ACTION_PLAN_SELECTION_NOT_IMPLEMENTED',$blockers);} 
  $before=($cur!==null&&$price!==null)?round((float)$cur*(float)$price,6):null;$removed=($prop!==null&&$price!==null)?round($prop*(float)$price,6):null;$remaining=($rem!==null&&$price!==null)?round($rem*(float)$price,6):null;$planId=$prop!==null?hash('sha256',json_encode(['position_id'=>$pos['position_id']??null,'management_candidate_id'=>$eval['management_candidate_id']??null,'policy_id'=>$eval['policy_id']??null,'policy_version'=>$eval['policy_version']??null,'rule_id'=>$eval['matched_rule']['rule_id']??null,'proposed_action'=>$action,'quantity_mode'=>$mode,'proposed_quantity'=>$prop,'remaining_quantity'=>$rem,'price_basis'=>['reference_price'=>$price,'observed_at'=>$snap['observed_at']??($state['observed_at']??null),'source'=>$snap['source']??($state['market_observation_id']??null)],'schema'=>$this->config['action_plan_schema_version'],'decision_at'=>$ctx['decision_at']??null],JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION)):null;
  $r=['schema_version'=>$this->config['action_plan_schema_version'],'status'=>$status,'position_id'=>$pos['position_id']??($eval['position_id']??null),'management_candidate_id'=>$eval['management_candidate_id']??null,'action_plan_id'=>$planId,'plan_scope'=>'management_action_reference_non_executable','eligibility'=>$elig,'proposed_management_action'=>$action,'quantity_plan'=>['mode'=>$mode,'current_quantity'=>$cur,'proposed_quantity_reference'=>$prop,'remaining_quantity_reference'=>$rem,'unit'=>'shares'],'price_basis'=>['status'=>$priceStatus,'reference_price'=>$price,'price_type'=>'current_reference_price','observed_at'=>$snap['observed_at']??($state['observed_at']??null),'source'=>$snap['source']??($state['market_observation_id']??null)],'position_impact_reference'=>['gross_notional_before'=>$before,'gross_notional_removed'=>$removed,'gross_notional_remaining'=>$remaining],'order'=>['status'=>'not_implemented','side'=>null,'order_type'=>null,'limit_price'=>null,'stop_price'=>null,'time_in_force'=>null,'client_order_id'=>null],'selection'=>['selected'=>false],'approval'=>['portfolio_approved'=>false,'production_approved'=>false,'execution_approved'=>false],'execution'=>['executable'=>false,'instruction'=>null],'reason_codes'=>$this->ordered($codes),'warnings'=>$this->ordered($warnings),'blockers'=>$this->ordered($blockers),'metadata'=>['policy_id'=>$eval['policy_id']??null,'policy_version'=>$eval['policy_version']??null,'matched_rule_id'=>$eval['matched_rule']['rule_id']??null]]; $this->validatePlan($r); return $r;}
 public function validatePlan(array $r):void{if(($r['schema_version']??null)!==$this->config['action_plan_schema_version'])throw new \InvalidArgumentException('bad action plan schema');if(!in_array($r['status'],['not_required','unavailable','blocked','parameter_ready','materialized_reference','invalid'],true))throw new \InvalidArgumentException('bad action plan status');if(($r['selection']['selected']??null)!==false||($r['approval']['portfolio_approved']??null)!==false||($r['execution']['executable']??null)!==false)throw new \InvalidArgumentException('action plan may not select approve execute');foreach(['side','order_type','limit_price','stop_price','time_in_force','client_order_id'] as $f)if(($r['order'][$f]??null)!==null)throw new \InvalidArgumentException('order forbidden');}
 protected function add(&$c,$code,&$target=null):void{if(!in_array($code,$c,true))$c[]=$code;if(is_array($target)&&!in_array($code,$target,true))$target[]=$code;} protected function ordered($c):array{sort($c);return array_values(array_unique($c));}
}
