<?php
namespace Tests\Unit;
use App\Services\Trading\ExposureAggregationService;
use Tests\TestCase;
class ExposureAggregationServiceTest extends TestCase
{
 public function test_unavailable_without_context_or_positions(): void{$r=(new ExposureAggregationService())->aggregate(['decision_at'=>$this->at()]);$this->assertSame('trading_exposure_aggregation_v1',$r['schema_version']);$this->assertSame('unavailable',$r['status']);$this->assertContains('PORTFOLIO_CONTEXT_UNAVAILABLE',$r['reason_codes']);$this->assertContains('PORTFOLIO_NO_EMPTY_PORTFOLIO_ASSUMPTION',$r['reason_codes']);}
 public function test_complete_aggregation_ticker_and_sector(): void{$r=(new ExposureAggregationService())->aggregate(['decision_at'=>$this->at(),'portfolio_context'=>$this->portfolio(),'position_snapshots'=>[$this->pos('p1','BUMI','Energy',10000,100,1000000,100000),$this->pos('p2','EXISTING','Finance',10000,100,1000000,100000)]]);$this->assertSame('aggregated_reference',$r['status']);$this->assertSame(2,$r['position_count']);$this->assertSame(2000000.0,$r['metrics']['gross_notional']);$this->assertSame(200000.0,$r['metrics']['gross_capital_at_risk']);$this->assertSame(1000000.0,$r['metrics']['ticker_exposure']['BUMI']['notional']);$this->assertSame(1000000.0,$r['metrics']['sector_exposure']['Energy']['notional']);}
 public function test_invalid_duplicate_currency_and_notional_mismatch(): void{$p=$this->portfolio();$a=$this->pos('p1','BUMI',null,1000,100,999,5000);$b=$this->pos('p1','DEWA',null,1000,100,100000,5000);$b['currency']='USD';$r=(new ExposureAggregationService())->aggregate(['decision_at'=>$this->at(),'portfolio_context'=>$p,'position_snapshots'=>[$a,$b]]);$this->assertSame('unavailable',$r['status']);$this->assertContains('PORTFOLIO_POSITION_SNAPSHOT_INVALID',$r['reason_codes']);$this->assertContains('PORTFOLIO_CURRENCY_MISMATCH',$r['reason_codes']);}
 public function test_schema_validation_rejects_duplicate_reasons(): void{$svc=new ExposureAggregationService();$r=$svc->aggregate(['decision_at'=>$this->at()]);$r['reason_codes'][]=$r['reason_codes'][0];$this->expectException(\InvalidArgumentException::class);$svc->validateExposureAggregation($r);} 
 protected function portfolio():array{return ['schema_version'=>'trading_portfolio_context_v1','status'=>'reference_only','portfolio_id'=>'synthetic-portfolio-1','base_currency'=>'IDR','capital_base'=>10000000.0,'available_cash'=>null,'as_of'=>$this->at(),'source'=>['type'=>'synthetic_test_fixture','identifier'=>'portfolio'],'approved_for_execution'=>false,'synthetic_test_only'=>true];}
 protected function pos($id,$ticker,$sector,$qty,$price,$notional,$risk):array{return ['schema_version'=>'trading_position_snapshot_v1','status'=>'reference_only','position_id'=>$id,'portfolio_id'=>'synthetic-portfolio-1','ticker'=>$ticker,'sector'=>$sector,'currency'=>'IDR','side'=>'long','quantity'=>$qty,'reference_price'=>$price,'reference_notional'=>$notional,'capital_at_risk'=>$risk,'risk_source'=>['type'=>'explicit_reference_input','identifier'=>$id.'-risk'],'as_of'=>$this->at(),'source'=>['type'=>'synthetic_test_fixture','identifier'=>$id],'approved_for_execution'=>false,'synthetic_test_only'=>true];}
 protected function at():string{return '2026-07-01T10:00:00+07:00';}
}
