<?php
namespace Tests\Unit;
use App\Services\Trading\PortfolioRiskEvaluationService;
use Tests\TestCase;
class PortfolioRiskEvaluationServiceTest extends TestCase
{
 public function test_unavailable_without_candidate(): void{$r=(new PortfolioRiskEvaluationService())->evaluate([]);$this->assertSame('trading_portfolio_risk_v1',$r['schema_version']);$this->assertSame('unavailable',$r['status']);$this->assertFalse($r['approved']);}
 public function test_valid_post_candidate_exposure_and_policy_pass(): void{$r=(new PortfolioRiskEvaluationService())->evaluate($this->ctx(5.0));$this->assertSame('evaluated_reference',$r['status']);$this->assertSame(2500000.0,$r['post_candidate_exposure']['gross_notional']);$this->assertSame(25.0,$r['post_candidate_exposure']['gross_notional_pct_of_capital']);$this->assertSame(210000.0,$r['post_candidate_exposure']['aggregate_capital_at_risk']);$this->assertSame(2.1,$r['post_candidate_exposure']['aggregate_capital_at_risk_pct']);$this->assertFalse($r['approved']);$this->assertContains('PORTFOLIO_RISK_EVALUATED_REFERENCE',$r['reason_codes']);}
 public function test_limit_exceeded_reference(): void{$r=(new PortfolioRiskEvaluationService())->evaluate($this->ctx(2.0));$this->assertSame('limit_exceeded_reference',$r['status']);$this->assertContains('PORTFOLIO_AGGREGATE_RISK_LIMIT_EXCEEDED',$r['reason_codes']);$this->assertFalse($r['approved']);}
 public function test_confidence_and_rr_do_not_change_result(): void{$a=(new PortfolioRiskEvaluationService())->evaluate($this->ctx(5.0)+['confidence'=>50,'rr'=>1.2]);$b=(new PortfolioRiskEvaluationService())->evaluate($this->ctx(5.0)+['confidence'=>95,'rr'=>9]);$this->assertSame($a['post_candidate_exposure'],$b['post_candidate_exposure']);}
 protected function ctx($limit):array{return ['action_candidate'=>['schema_version'=>'trading_action_candidate_v1','status'=>'candidate_ready','candidate_id'=>'cid','intent'=>'long_entry'],'capital_risk'=>['status'=>'evaluated_reference','metrics'=>['maximum_loss_amount'=>10000.0],'metadata'=>['currency'=>'IDR']],'position_sizing'=>['status'=>'reference_sized','metrics'=>['reference_notional'=>500000.0]],'execution_readiness'=>['status'=>'partial','constraint_evaluation'=>['metrics'=>['reference_notional'=>500000.0]]],'portfolio_context'=>['schema_version'=>'trading_portfolio_context_v1','status'=>'reference_only','portfolio_id'=>'synthetic-portfolio-1','base_currency'=>'IDR','capital_base'=>10000000.0],'exposure_aggregation'=>['schema_version'=>'trading_exposure_aggregation_v1','status'=>'aggregated_reference','portfolio_id'=>'synthetic-portfolio-1','position_count'=>2,'metrics'=>['gross_notional'=>2000000.0,'gross_capital_at_risk'=>200000.0,'ticker_exposure'=>['BUMI'=>['notional'=>0.0,'capital_at_risk'=>0.0]]]],'portfolio_risk_policy'=>['schema_version'=>'trading_portfolio_risk_policy_v1','status'=>'reference_only','portfolio_id'=>'synthetic-portfolio-1','candidate_id'=>'cid','policy_version'=>'portfolio_reference_policy_v1','limits'=>['maximum_aggregate_capital_at_risk_pct'=>$limit,'maximum_single_ticker_notional_pct'=>25.0,'maximum_single_ticker_capital_at_risk_pct'=>2.0],'source'=>['type'=>'synthetic_test_fixture','identifier'=>'policy'],'approved_for_execution'=>false,'synthetic_test_only'=>true],'candidate_ticker'=>'BUMI'];}
}
