<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementActionPolicyService;
use Tests\TestCase;
class PositionManagementActionPolicyServiceTest extends TestCase
{
 protected function candidate($type='protection_breach_review'){return ['schema_version'=>'trading_position_management_candidate_v1','status'=>'policy_hypothesis','candidate_id'=>str_repeat('a',64),'candidate_type'=>$type,'position_id'=>'position-bumi-1','ticker'=>'BUMI','position_side'=>'long'];}
 protected function risk(){return ['status'=>'condition_risk_observed'];}
 protected function review(){return ['status'=>'review_context_ready'];}
 protected function policy($rule=[]){return ['schema_version'=>'trading_position_management_action_policy_v1','status'=>'reference_only','policy_id'=>'policy-1','policy_version'=>'v1','position_id'=>'position-bumi-1','ticker'=>'BUMI','management_candidate_id'=>str_repeat('a',64),'supported_side'=>'long','rules'=>[array_merge(['rule_id'=>'r1','candidate_type'=>'protection_breach_review','proposed_action'=>'exit_position','quantity_mode'=>'full_position','explicit_units'=>null,'explicit_fraction'=>null,'enabled'=>true,'priority'=>100],$rule)],'source'=>['type'=>'synthetic_test_fixture','identifier'=>'x'],'approved_for_selection'=>false,'approved_for_portfolio_mutation'=>false,'approved_for_execution'=>false,'synthetic_test_only'=>true];}
 public function test_no_policy_is_unavailable():void{$r=(new PositionManagementActionPolicyService())->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review()]);$this->assertSame('unavailable',$r['status']);$this->assertNull($r['proposed_action']);}
 public function test_invalid_schema_and_unsupported_action_are_invalid():void{$svc=new PositionManagementActionPolicyService();$bad=$this->policy();$bad['schema_version']='x';$this->assertSame('invalid',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$bad])['status']);$bad=$this->policy(['proposed_action'=>'sell']);$this->assertSame('invalid',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$bad])['status']);}
 public function test_identity_mismatch_and_no_matching_rule():void{$svc=new PositionManagementActionPolicyService();$p=$this->policy();$p['ticker']='DEWA';$this->assertSame('blocked',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$p])['status']);$this->assertSame('no_matching_rule',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate('target_reached_review'),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$this->policy()])['status']);}
 public function test_stop_and_target_rules_are_reference_only():void{$svc=new PositionManagementActionPolicyService();$stop=$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$this->policy()]);$this->assertSame('matched_reference_rule',$stop['status']);$this->assertSame('exit_position',$stop['proposed_action']);$targetPolicy=$this->policy(['candidate_type'=>'target_reached_review','proposed_action'=>'reduce_position','quantity_mode'=>'explicit_fraction','explicit_fraction'=>0.5]);$target=$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate('target_reached_review'),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$targetPolicy]);$this->assertSame('reduce_position',$target['proposed_action']);$this->assertContains('POSITION_MANAGEMENT_ACTION_POLICY_SELECTION_NOT_APPROVED',$target['blockers']);}
 public function test_duplicate_rule_priority_and_approval_flags_rejected():void{$svc=new PositionManagementActionPolicyService();$p=$this->policy();$p['rules'][]=$p['rules'][0];$this->assertSame('invalid',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$p])['status']);$p=$this->policy();$p['approved_for_selection']=true;$this->assertSame('invalid',$svc->evaluate(['decision_scope'=>'position_management','management_candidate'=>$this->candidate(),'management_risk'=>$this->risk(),'review_plan'=>$this->review(),'management_action_policy'=>$p])['status']);}
}
