<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementPortfolioApprovalService;
use Tests\TestCase;
class PositionManagementPortfolioApprovalServiceTest extends TestCase
{protected function candidate(){return ['status'=>'policy_hypothesis','candidate_id'=>'c1','position_id'=>'position-bumi-1'];}protected function plan($action='exit_position',$q=1000){return ['status'=>'materialized_reference','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','action_plan_id'=>'plan1','proposed_management_action'=>$action,'quantity_plan'=>['proposed_quantity_reference'=>$q,'remaining_quantity_reference'=>$action==='exit_position'?0:500]];}protected function impact(){return ['status'=>'simulated_reference','portfolio_impact'=>['status'=>'simulated_reference']];}protected function policy(){return ['status'=>'eligible_for_authorization','policy_id'=>'mp1','portfolio_id'=>'pf1'];}protected function auth($status='valid_reference_authorization'){return ['status'=>$status,'authorization_decision'=>$status==='denied_reference'?'deny_reference':'approve_reference'];}protected function approve($auth=null,$plan=null,$impact=null){return (new PositionManagementPortfolioApprovalService())->approve(['management_candidate'=>$this->candidate(),'action_plan'=>$plan??$this->plan(),'impact_simulation'=>$impact??$this->impact(),'management_approval_policy_evaluation'=>$this->policy(),'management_authorization_validation'=>$auth]);}
 public function test_missing_inputs():void{$svc=new PositionManagementPortfolioApprovalService();$this->assertSame('unavailable',$svc->approve([])['status']);$this->assertSame('unavailable',$svc->approve(['management_candidate'=>$this->candidate()])['status']);}
 public function test_eligible_without_authorization_is_not_auto_approved():void{$r=$this->approve(null);$this->assertSame('eligible_for_reference_approval',$r['status']);$this->assertFalse($r['approval_result']['reference_approved']);$this->assertContains('POSITION_MANAGEMENT_NO_AUTO_APPROVAL_FROM_RISK_REDUCTION',$r['blockers']);}
 public function test_approved_reference_full_and_partial_keep_execution_false():void{$r=$this->approve($this->auth());$this->assertSame('approved_reference',$r['status']);$this->assertTrue($r['approval_result']['reference_approved']);$this->assertFalse($r['approval_result']['production_approved']);$this->assertFalse($r['approval_result']['execution_approved']);$this->assertNull($r['approved_management_action']);$p=$this->approve($this->auth(),$this->plan('reduce_position',500));$this->assertSame('reduce_position',$p['reference_proposal_snapshot']['proposed_management_action']);$this->assertSame(500,$p['reference_proposal_snapshot']['proposed_quantity_reference']);}
 public function test_denied_expired_invalid_and_impact_failure():void{$this->assertSame('denied_reference',$this->approve($this->auth('denied_reference'))['status']);$this->assertSame('blocked',$this->approve($this->auth('expired'))['status']);$this->assertSame('blocked',$this->approve($this->auth('invalid'))['status']);$this->assertSame('blocked',$this->approve($this->auth(),null,['status'=>'partial'])['status']);}
}
