<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementAuthorizationService;
use Tests\TestCase;
class PositionManagementAuthorizationServiceTest extends TestCase
{protected function policy(){return ['schema_version'=>'trading_position_management_approval_policy_evaluation_v1','status'=>'eligible_for_authorization','policy_id'=>'mp1','policy_version'=>'v1','portfolio_id'=>'pf1','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','metadata'=>['management_approval_context_fingerprint'=>'fp']];}protected function plan(){return ['action_plan_id'=>'plan1','position_id'=>'position-bumi-1','proposed_management_action'=>'exit_position','quantity_plan'=>['proposed_quantity_reference'=>1000]];}protected function impact(){return ['action_plan_id'=>'plan1','position_id'=>'position-bumi-1'];}protected function auth(array $over=[]){return array_replace_recursive(['schema_version'=>'trading_position_management_authorization_v1','status'=>'reference_only','authorization_id'=>'auth1','authorization_type'=>'management_reference_approval','authorization_decision'=>'approve_reference','approval_scope'=>'management_action_reference','portfolio_id'=>'pf1','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','action_plan_id'=>'plan1','proposed_management_action'=>'exit_position','proposed_quantity_reference'=>1000,'policy_id'=>'mp1','policy_version'=>'v1','approval_context_fingerprint'=>'fp','issued_by'=>['type'=>'synthetic_test_fixture','identifier'=>'issuer'],'issued_at'=>'2026-07-01T09:00:00+07:00','expires_at'=>'2026-07-01T11:00:00+07:00','production_authority'=>false,'execution_authority'=>false,'synthetic_test_only'=>true],$over);}protected function val($auth){return (new PositionManagementAuthorizationService())->validate(['decision_at'=>'2026-07-01T10:00:00+07:00','management_authorization'=>$auth,'management_approval_policy_evaluation'=>$this->policy(),'action_plan'=>$this->plan(),'impact_simulation'=>$this->impact()]);}
 public function test_no_and_invalid_authorization():void{$this->assertSame('unavailable',$this->val(null)['status']);$a=$this->auth(['schema_version'=>'x']);$this->assertSame('invalid',$this->val($a)['status']);}
 public function test_mismatches_are_invalid():void{foreach([['portfolio_id','x'],['position_id','x'],['management_candidate_id','x'],['action_plan_id','x'],['proposed_management_action','reduce_position'],['proposed_quantity_reference',1],['policy_id','x'],['policy_version','x'],['approval_context_fingerprint','x']] as [$k,$v]){$this->assertSame('invalid',$this->val($this->auth([$k=>$v]))['status']);}}
 public function test_time_and_authority_validation():void{$this->assertSame('invalid',$this->val($this->auth(['issued_at'=>'2026-07-01T10:30:00+07:00']))['status']);$this->assertSame('invalid',$this->val($this->auth(['expires_at'=>'2026-07-01T08:00:00+07:00']))['status']);$this->assertSame('expired',$this->val($this->auth(['expires_at'=>'2026-07-01T09:30:00+07:00']))['status']);$this->assertSame('invalid',$this->val($this->auth(['production_authority'=>true]))['status']);$this->assertSame('invalid',$this->val($this->auth(['execution_authority'=>true]))['status']);}
 public function test_supported_decisions():void{$this->assertSame('valid_reference_authorization',$this->val($this->auth())['status']);$this->assertSame('denied_reference',$this->val($this->auth(['authorization_decision'=>'deny_reference']))['status']);$this->assertSame('review_only',$this->val($this->auth(['authorization_decision'=>'review_only']))['status']);$this->assertTrue($this->val($this->auth())['metadata']['not_cryptographically_verified']);}
}
