<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementApprovalPolicyService;
use Tests\TestCase;
class PositionManagementApprovalPolicyServiceTest extends TestCase
{protected function chain():array{$candidate=['schema_version'=>'trading_position_management_candidate_v1','status'=>'policy_hypothesis','candidate_id'=>'c1','candidate_type'=>'protection_breach_review','position_id'=>'position-bumi-1'];$risk=['schema_version'=>'trading_position_management_risk_v1','status'=>'condition_risk_observed'];$review=['schema_version'=>'trading_position_management_review_plan_v1','status'=>'review_context_ready'];$ap=['schema_version'=>'trading_position_management_action_policy_evaluation_v1','status'=>'matched_reference_rule','policy_id'=>'ap1','policy_version'=>'v1','matched_rule'=>['rule_id'=>'r1']];$plan=['schema_version'=>'trading_position_management_action_plan_v1','status'=>'materialized_reference','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','action_plan_id'=>'plan1','proposed_management_action'=>'exit_position','quantity_plan'=>['mode'=>'full_position','proposed_quantity_reference'=>1000,'remaining_quantity_reference'=>0],'price_basis'=>['reference_price'=>89]];$impact=['schema_version'=>'trading_position_management_impact_v1','status'=>'simulated_reference','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','action_plan_id'=>'plan1','position_impact'=>['gross_notional_before'=>89000,'gross_notional_removed'=>89000,'gross_notional_remaining'=>0],'portfolio_impact'=>['status'=>'simulated_reference','portfolio_id'=>'pf1','gross_notional_before'=>2000000,'gross_notional_after_reference'=>1911000]];return compact('candidate','risk','review','ap','plan','impact');}
 protected function policy($planId='plan1',array $over=[]):array{return array_replace_recursive(['schema_version'=>'trading_position_management_approval_policy_v1','status'=>'reference_only','policy_id'=>'mp1','policy_version'=>'v1','approval_scope'=>'management_action_reference','portfolio_id'=>'pf1','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','action_plan_id'=>$planId,'proposed_management_action'=>'exit_position','requirements'=>['management_candidate_valid'=>true,'management_risk_evaluated'=>true,'review_context_ready'=>true,'action_policy_matched'=>true,'action_plan_materialized'=>true,'impact_simulated'=>true,'position_impact_reconciled'=>true,'portfolio_impact_available'=>true,'portfolio_identity_reconciled'=>true,'authorization_required'=>true],'source'=>['type'=>'synthetic_test_fixture','identifier'=>'p'],'approved_for_production'=>false,'approved_for_execution'=>false,'synthetic_test_only'=>true],$over);} 
 protected function evalWith($policy):array{$c=$this->chain();return (new PositionManagementApprovalPolicyService())->evaluate(['decision_scope'=>'position_management','decision_at'=>'2026-07-01T10:00:00+07:00','portfolio_context'=>['portfolio_id'=>'pf1'],'management_candidate'=>$c['candidate'],'management_risk'=>$c['risk'],'review_plan'=>$c['review'],'action_policy_evaluation'=>$c['ap'],'action_plan'=>$c['plan'],'impact_simulation'=>$c['impact'],'management_approval_policy'=>$policy]);}
 public function test_no_policy_and_invalid_schema():void{$this->assertSame('unavailable',$this->evalWith(null)['status']);$p=$this->policy();$p['schema_version']='x';$this->assertSame('invalid',$this->evalWith($p)['status']);}
 public function test_unsupported_scope_unknown_requirement_and_identity_mismatch():void{$p=$this->policy(over:['approval_scope'=>'entry_reference']);$this->assertSame('invalid',$this->evalWith($p)['status']);$p=$this->policy(over:['requirements'=>['unknown'=>true]]);$this->assertSame('invalid',$this->evalWith($p)['status']);$this->assertSame('blocked',$this->evalWith($this->policy('other'))['status']);}
 public function test_missing_evidence_and_portfolio_impact_required():void{$c=$this->chain();$c['impact']['portfolio_impact']['status']='unavailable';$r=(new PositionManagementApprovalPolicyService())->evaluate(['portfolio_context'=>['portfolio_id'=>'pf1'],'management_candidate'=>$c['candidate'],'management_risk'=>$c['risk'],'review_plan'=>$c['review'],'action_policy_evaluation'=>$c['ap'],'action_plan'=>$c['plan'],'impact_simulation'=>$c['impact'],'management_approval_policy'=>$this->policy()]);$this->assertSame('blocked',$r['status']);$this->assertFalse($r['all_required_checks_passed']);}
 public function test_full_valid_chain_is_eligible_not_approved_and_deterministic():void{$a=$this->evalWith($this->policy());$b=$this->evalWith($this->policy());$this->assertSame('eligible_for_authorization',$a['status']);$this->assertTrue($a['all_required_checks_passed']);$this->assertSame($a,$b);$this->assertArrayHasKey('management_approval_context_fingerprint',$a['metadata']);}
}
