<?php
namespace Tests\Unit;
use App\Services\Trading\PositionStateEvaluationService;
use Tests\TestCase;
class PositionStateEvaluationServiceTest extends TestCase
{public function test_no_position_unavailable():void{$r=(new PositionStateEvaluationService())->evaluate(['decision_at'=>$this->at(),'ticker'=>'BUMI']);$this->assertSame('trading_position_state_v1',$r['schema_version']);$this->assertSame('unavailable',$r['status']);$this->assertContains('MANAGED_POSITION_UNAVAILABLE',$r['reason_codes']);}
public function test_valid_monitoring_negative_pnl():void{$r=(new PositionStateEvaluationService())->evaluate($this->ctx(95));$this->assertSame('monitoring_reference',$r['status']);$this->assertSame(-5.0,$r['metrics']['unrealized_pnl_pct']);$this->assertSame(-5000.0,$r['metrics']['unrealized_pnl_amount']);$this->assertFalse($r['protection_checks']['stop_reference_breached']);$this->assertFalse($r['protection_checks']['target_reference_reached']);}
public function test_stop_breach_and_target_reach():void{$stop=(new PositionStateEvaluationService())->evaluate($this->ctx(89));$this->assertSame('condition_observed',$stop['status']);$this->assertTrue($stop['protection_checks']['stop_reference_breached']);$this->assertContains('POSITION_STOP_REFERENCE_BREACHED',$stop['reason_codes']);$target=(new PositionStateEvaluationService())->evaluate($this->ctx(111));$this->assertSame('condition_observed',$target['status']);$this->assertTrue($target['protection_checks']['target_reference_reached']);}
public function test_missing_protection_partial_and_validator():void{$ctx=$this->ctx(105);unset($ctx['managed_position']['existing_protection']);$r=(new PositionStateEvaluationService())->evaluate($ctx);$this->assertSame('partial',$r['status']);$this->assertContains('POSITION_PROTECTION_REFERENCE_UNAVAILABLE',$r['reason_codes']);$svc=new PositionStateEvaluationService();$r['reason_codes'][]=$r['reason_codes'][0];$this->expectException(\InvalidArgumentException::class);$svc->validatePositionState($r);} protected function ctx($price):array{return ['decision_at'=>$this->at(),'ticker'=>'BUMI','managed_position'=>$this->pos(),'market_observation'=>$this->obs($price)];} protected function pos():array{return ['schema_version'=>'trading_managed_position_v1','status'=>'open_reference','position_id'=>'position-bumi-1','ticker'=>'BUMI','side'=>'long','quantity'=>1000,'currency'=>'IDR','entry_price'=>100,'opened_at'=>'2026-06-20T09:00:00+07:00','existing_protection'=>['stop_reference'=>['status'=>'available','price'=>90,'source'=>['type'=>'explicit_input','identifier'=>'stop']], 'target_reference'=>['status'=>'available','price'=>110,'source'=>['type'=>'explicit_input','identifier'=>'target']]],'source'=>['type'=>'synthetic_test_fixture','identifier'=>'managed-position-1'],'approved_for_execution'=>false,'synthetic_test_only'=>true];} protected function obs($price):array{return ['schema_version'=>'trading_position_market_observation_v1','status'=>'reference_only','ticker'=>'BUMI','price'=>$price,'currency'=>'IDR','observed_at'=>$this->at(),'price_type'=>'reference_market_price','source'=>['type'=>'synthetic_test_fixture','identifier'=>'obs'],'approved_for_execution'=>false,'synthetic_test_only'=>true];} protected function at():string{return '2026-07-01T10:00:00+07:00';}}
