<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementActionPlanService;
use Tests\TestCase;
class PositionManagementActionPlanServiceTest extends TestCase
{protected function eval($action='exit_position',$mode='full_position',$rule=[]){return ['schema_version'=>'trading_position_management_action_policy_evaluation_v1','status'=>'matched_reference_rule','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','policy_id'=>'p1','policy_version'=>'v1','matched_rule'=>array_merge(['rule_id'=>'r1','proposed_action'=>$action,'quantity_mode'=>$mode],$rule),'proposed_action'=>$action,'quantity_mode'=>$mode];}protected function pos(){return ['position_id'=>'position-bumi-1','ticker'=>'BUMI','quantity'=>1000];}protected function state($price=89){return ['position_id'=>'position-bumi-1','price_snapshot'=>['current_reference_price'=>$price,'observed_at'=>'2026-07-01T10:00:00+07:00','source'=>'fixture']];}
 public function test_policy_unavailable_blocks_plan():void{$r=(new PositionManagementActionPlanService())->build([]);$this->assertSame('unavailable',$r['status']);$this->assertNull($r['proposed_management_action']);}
 public function test_full_exit_quantity_and_notional():void{$r=(new PositionManagementActionPlanService())->build(['action_policy_evaluation'=>$this->eval(),'managed_position'=>$this->pos(),'position_state'=>$this->state(),'management_risk'=>['status'=>'condition_risk_observed']]);$this->assertSame('materialized_reference',$r['status']);$this->assertSame(1000.0,$r['quantity_plan']['proposed_quantity_reference']);$this->assertSame(0.0,$r['quantity_plan']['remaining_quantity_reference']);$this->assertSame(89000.0,$r['position_impact_reference']['gross_notional_removed']);$this->assertNull($r['order']['order_type']);$this->assertFalse($r['selection']['selected']);}
 public function test_partial_units_and_fraction():void{$svc=new PositionManagementActionPlanService();$u=$svc->build(['action_policy_evaluation'=>$this->eval('reduce_position','explicit_units',['explicit_units'=>250]),'managed_position'=>$this->pos(),'position_state'=>$this->state(111),'management_risk'=>['status'=>'condition_risk_observed']]);$this->assertSame(250.0,$u['quantity_plan']['proposed_quantity_reference']);$f=$svc->build(['action_policy_evaluation'=>$this->eval('reduce_position','explicit_fraction',['explicit_fraction'=>0.5]),'managed_position'=>$this->pos(),'position_state'=>$this->state(111),'management_risk'=>['status'=>'condition_risk_observed']]);$this->assertSame(500.0,$f['quantity_plan']['proposed_quantity_reference']);$this->assertSame(55500.0,$f['position_impact_reference']['gross_notional_remaining']);}
 public function test_invalid_quantities_rejected():void{$svc=new PositionManagementActionPlanService();$r=$svc->build(['action_policy_evaluation'=>$this->eval('reduce_position','explicit_units',['explicit_units'=>1000]),'managed_position'=>$this->pos(),'position_state'=>$this->state(),'management_risk'=>['status'=>'condition_risk_observed']]);$this->assertSame('invalid',$r['status']);$this->assertContains('POSITION_MANAGEMENT_ACTION_PLAN_QUANTITY_INVALID',$r['blockers']);}
}
