<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementCandidateService;
use Tests\TestCase;
class PositionManagementCandidateServiceTest extends TestCase
{protected function state(array $over=[]):array{return array_replace_recursive(['schema_version'=>'trading_position_state_v1','status'=>'condition_observed','position_id'=>'position-bumi-1','ticker'=>'BUMI','position_side'=>'long','lifecycle'=>['observed_at'=>'2026-07-01T10:00:00+07:00'],'protection_checks'=>['stop_reference_available'=>true,'stop_reference_breached'=>true,'target_reference_available'=>true,'target_reference_reached'=>false],'reason_codes'=>['POSITION_STOP_REFERENCE_BREACHED']],$over);}protected function eval(array $over=[]):array{return array_replace_recursive(['schema_version'=>'trading_position_management_policy_evaluation_v1','status'=>'matched_reference_rule','position_id'=>'position-bumi-1','policy_id'=>'policy-1','policy_version'=>'v1','state_condition'=>'stop_reference_breached','matched_rule'=>['rule_id'=>'review-stop','condition'=>'stop_reference_breached','candidate_type'=>'protection_breach_review','priority'=>1,'enabled'=>true],'matched_rules'=>[],'candidate_type'=>'protection_breach_review','reason_codes'=>[]],$over);}public function test_unavailable_and_no_condition():void{$svc=new PositionManagementCandidateService();$r=$svc->form(['position_state'=>null,'policy_evaluation'=>null]);$this->assertSame('unavailable',$r['status']);$n=$svc->form(['position_state'=>$this->state(['status'=>'monitoring_reference']),'policy_evaluation'=>$this->eval(['status'=>'no_condition','matched_rule'=>null,'candidate_type'=>null,'state_condition'=>null])]);$this->assertSame('unavailable',$n['status']);$this->assertContains('POSITION_MANAGEMENT_NO_IMPLICIT_HOLD',$n['warnings']);}
public function test_review_hypotheses_and_non_executable():void{$svc=new PositionManagementCandidateService();foreach([['protection_breach_review','stop_reference_breached'],['target_reached_review','target_reference_reached'],['protection_missing_review','protection_reference_missing']] as [$type,$condition]){$e=$this->eval(['state_condition'=>$condition,'candidate_type'=>$type,'matched_rule'=>['rule_id'=>'r-'.$type,'condition'=>$condition,'candidate_type'=>$type,'priority'=>1,'enabled'=>true]]);$r=$svc->form(['position_state'=>$this->state(),'policy_evaluation'=>$e,'decision_at'=>'2026-07-01T10:00:00+07:00']);$this->assertSame('policy_hypothesis',$r['status']);$this->assertMatchesRegularExpression('/^[a-f0-9]{64}$/',$r['candidate_id']);$this->assertFalse($r['execution']['executable']);$this->assertNull($r['execution']['instruction']);$this->assertNotContains($r['candidate_type'],['HOLD','SELL','CUT_LOSS']);}}
public function test_candidate_id_changes_with_evidence_policy_and_rule():void{$svc=new PositionManagementCandidateService();$a=$svc->form(['position_state'=>$this->state(),'policy_evaluation'=>$this->eval(),'decision_at'=>'2026-07-01T10:00:00+07:00']);$b=$svc->form(['position_state'=>$this->state(['lifecycle'=>['observed_at'=>'2026-07-01T10:01:00+07:00']]),'policy_evaluation'=>$this->eval(),'decision_at'=>'2026-07-01T10:00:00+07:00']);$c=$svc->form(['position_state'=>$this->state(),'policy_evaluation'=>$this->eval(['policy_version'=>'v2']),'decision_at'=>'2026-07-01T10:00:00+07:00']);$d=$svc->form(['position_state'=>$this->state(),'policy_evaluation'=>$this->eval(['matched_rule'=>['rule_id'=>'other','condition'=>'stop_reference_breached','candidate_type'=>'protection_breach_review','priority'=>1,'enabled'=>true]]),'decision_at'=>'2026-07-01T10:00:00+07:00']);$this->assertNotSame($a['candidate_id'],$b['candidate_id']);$this->assertNotSame($a['candidate_id'],$c['candidate_id']);$this->assertNotSame($a['candidate_id'],$d['candidate_id']);}
public function test_stale_observation_blocked_and_schema_validation():void{$svc=new PositionManagementCandidateService();$r=$svc->form(['position_state'=>$this->state(['reason_codes'=>['POSITION_MARKET_OBSERVATION_STALE']]),'policy_evaluation'=>$this->eval(),'decision_at'=>'2026-07-01T10:00:00+07:00']);$this->assertSame('blocked',$r['status']);$this->assertContains('POSITION_MANAGEMENT_STALE_OBSERVATION_REVIEW_BLOCKED',$r['blockers']);$r['execution']['executable']=true;$this->expectException(\InvalidArgumentException::class);$svc->validateCandidate($r);}}
