<?php
namespace Tests\Unit;
use App\Services\Trading\PositionManagementImpactSimulationService;
use Tests\TestCase;
class PositionManagementImpactSimulationServiceTest extends TestCase
{protected function plan($action='exit_position'){return ['schema_version'=>'trading_position_management_action_plan_v1','status'=>'materialized_reference','position_id'=>'position-bumi-1','management_candidate_id'=>'c1','proposed_management_action'=>$action,'quantity_plan'=>['current_quantity'=>1000,'proposed_quantity_reference'=>$action==='exit_position'?1000:500,'remaining_quantity_reference'=>$action==='exit_position'?0:500],'price_basis'=>['reference_price'=>$action==='exit_position'?89:111],'position_impact_reference'=>['gross_notional_before'=>$action==='exit_position'?89000:111000,'gross_notional_removed'=>$action==='exit_position'?89000:55500,'gross_notional_remaining'=>$action==='exit_position'?0:55500]];}protected function pos(){return ['position_id'=>'position-bumi-1','ticker'=>'BUMI','quantity'=>1000,'currency'=>'IDR'];}
 public function test_no_action_plan_unavailable():void{$r=(new PositionManagementImpactSimulationService())->simulate([]);$this->assertSame('unavailable',$r['status']);$this->assertNull($r['cash_and_pnl']['realized_pnl']);}
 public function test_full_exit_and_partial_local_impact():void{$svc=new PositionManagementImpactSimulationService();$full=$svc->simulate(['action_plan'=>$this->plan(),'managed_position'=>$this->pos()]);$this->assertSame('simulated_reference',$full['status']);$this->assertSame(89000,$full['position_impact']['gross_notional_removed']);$part=$svc->simulate(['action_plan'=>$this->plan('reduce_position'),'managed_position'=>$this->pos()]);$this->assertSame(55500,$part['position_impact']['gross_notional_remaining']);$this->assertFalse($part['approved']);}
 public function test_portfolio_and_capital_risk_impact():void{$r=(new PositionManagementImpactSimulationService())->simulate(['action_plan'=>$this->plan(),'managed_position'=>$this->pos(),'portfolio_context'=>['portfolio_id'=>'pf1'],'exposure_aggregation'=>['portfolio_id'=>'pf1','gross_notional'=>2000000,'gross_capital_at_risk'=>200000,'position_count'=>3],'portfolio_position_snapshot'=>['position_id'=>'position-bumi-1','ticker'=>'BUMI','currency'=>'IDR','capital_at_risk'=>10000,'position_count_policy'=>'full_removal']]);$this->assertSame(1911000.0,$r['portfolio_impact']['gross_notional_after_reference']);$this->assertSame(190000.0,$r['portfolio_impact']['gross_capital_at_risk_after_reference']);$this->assertSame(2,$r['portfolio_impact']['position_count_after_reference']);$this->assertNull($r['cash_and_pnl']['gross_proceeds']);}
 public function test_snapshot_mismatch_blocks_portfolio_only():void{$r=(new PositionManagementImpactSimulationService())->simulate(['action_plan'=>$this->plan(),'managed_position'=>$this->pos(),'portfolio_context'=>['portfolio_id'=>'pf1'],'exposure_aggregation'=>['portfolio_id'=>'pf1','gross_notional'=>2000000],'portfolio_position_snapshot'=>['position_id'=>'x','ticker'=>'BUMI','currency'=>'IDR']]);$this->assertSame('partial',$r['status']);$this->assertSame('blocked',$r['portfolio_impact']['status']);}
}
